[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
counter = "0.5.7"
itertools = "0.12.0"
maplit = "1.0.2"
num = "0.4.1"
range-set = "0.0.10"
rangemap = "1.4.0"
rayon = "1.8.0"
regex = "1.10.2"
serde_json = "1.0.108"
